// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_day_holidays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBusinessDayHolidaysByVersion = `-- name: ListBusinessDayHolidaysByVersion :many
SELECT calendar_version, holiday_date, label, source_note
FROM business_day_holidays
WHERE calendar_version = $1
ORDER BY holiday_date ASC
`

type ListBusinessDayHolidaysByVersionRow struct {
	CalendarVersion string      `json:"calendar_version"`
	HolidayDate     pgtype.Date `json:"holiday_date"`
	Label           string      `json:"label"`
	SourceNote      string      `json:"source_note"`
}

func (q *Queries) ListBusinessDayHolidaysByVersion(ctx context.Context, calendarVersion string) ([]ListBusinessDayHolidaysByVersionRow, error) {
	rows, err := q.db.Query(ctx, listBusinessDayHolidaysByVersion, calendarVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBusinessDayHolidaysByVersionRow
	for rows.Next() {
		var i ListBusinessDayHolidaysByVersionRow
		if err := rows.Scan(
			&i.CalendarVersion,
			&i.HolidayDate,
			&i.Label,
			&i.SourceNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
