// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: complaint_cases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComplaintCase = `-- name: CreateComplaintCase :one
INSERT INTO complaint_cases (
    tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, idempotency_key
) VALUES ($1, $2, $3, 'open', $4, $5, $6, $7)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
`

type CreateComplaintCaseParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	InteractionID   pgtype.UUID        `json:"interaction_id"`
	RedecoCause     string             `json:"redeco_cause"`
	OpenedAt        pgtype.Timestamptz `json:"opened_at"`
	SlaDueAt        pgtype.Timestamptz `json:"sla_due_at"`
	CalendarVersion string             `json:"calendar_version"`
	IdempotencyKey  string             `json:"idempotency_key"`
}

func (q *Queries) CreateComplaintCase(ctx context.Context, arg CreateComplaintCaseParams) (ComplaintCase, error) {
	row := q.db.QueryRow(ctx, createComplaintCase,
		arg.TenantID,
		arg.InteractionID,
		arg.RedecoCause,
		arg.OpenedAt,
		arg.SlaDueAt,
		arg.CalendarVersion,
		arg.IdempotencyKey,
	)
	var i ComplaintCase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionID,
		&i.RedecoCause,
		&i.State,
		&i.OpenedAt,
		&i.SlaDueAt,
		&i.CalendarVersion,
		&i.ReviewExpiresAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplaintCase = `-- name: GetComplaintCase :one
SELECT id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
FROM complaint_cases
WHERE tenant_id = $1 AND id = $2
`

type GetComplaintCaseParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetComplaintCase(ctx context.Context, arg GetComplaintCaseParams) (ComplaintCase, error) {
	row := q.db.QueryRow(ctx, getComplaintCase, arg.TenantID, arg.ID)
	var i ComplaintCase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionID,
		&i.RedecoCause,
		&i.State,
		&i.OpenedAt,
		&i.SlaDueAt,
		&i.CalendarVersion,
		&i.ReviewExpiresAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplaintCaseByIdempotencyKey = `-- name: GetComplaintCaseByIdempotencyKey :one
SELECT id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
FROM complaint_cases
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetComplaintCaseByIdempotencyKeyParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetComplaintCaseByIdempotencyKey(ctx context.Context, arg GetComplaintCaseByIdempotencyKeyParams) (ComplaintCase, error) {
	row := q.db.QueryRow(ctx, getComplaintCaseByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i ComplaintCase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionID,
		&i.RedecoCause,
		&i.State,
		&i.OpenedAt,
		&i.SlaDueAt,
		&i.CalendarVersion,
		&i.ReviewExpiresAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredReviewComplaintCases = `-- name: ListExpiredReviewComplaintCases :many
SELECT id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
FROM complaint_cases
WHERE tenant_id = $1 AND state = 'awaiting_review' AND review_expires_at <= $2
ORDER BY review_expires_at ASC
LIMIT $3
`

type ListExpiredReviewComplaintCasesParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ReviewExpiresAt pgtype.Timestamptz `json:"review_expires_at"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) ListExpiredReviewComplaintCases(ctx context.Context, arg ListExpiredReviewComplaintCasesParams) ([]ComplaintCase, error) {
	rows, err := q.db.Query(ctx, listExpiredReviewComplaintCases, arg.TenantID, arg.ReviewExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplaintCase
	for rows.Next() {
		var i ComplaintCase
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InteractionID,
			&i.RedecoCause,
			&i.State,
			&i.OpenedAt,
			&i.SlaDueAt,
			&i.CalendarVersion,
			&i.ReviewExpiresAt,
			&i.ResolvedAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenComplaintCases = `-- name: ListOpenComplaintCases :many
SELECT id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
FROM complaint_cases
WHERE tenant_id = $1 AND state = 'open'
ORDER BY opened_at ASC
LIMIT $2
`

type ListOpenComplaintCasesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListOpenComplaintCases(ctx context.Context, arg ListOpenComplaintCasesParams) ([]ComplaintCase, error) {
	rows, err := q.db.Query(ctx, listOpenComplaintCases, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplaintCase
	for rows.Next() {
		var i ComplaintCase
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InteractionID,
			&i.RedecoCause,
			&i.State,
			&i.OpenedAt,
			&i.SlaDueAt,
			&i.CalendarVersion,
			&i.ReviewExpiresAt,
			&i.ResolvedAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLADueComplaintCases = `-- name: ListSLADueComplaintCases :many
SELECT id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
FROM complaint_cases
WHERE tenant_id = $1 AND state IN ('open', 'awaiting_review') AND sla_due_at <= $2
ORDER BY sla_due_at ASC
LIMIT $3
`

type ListSLADueComplaintCasesParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	SlaDueAt pgtype.Timestamptz `json:"sla_due_at"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) ListSLADueComplaintCases(ctx context.Context, arg ListSLADueComplaintCasesParams) ([]ComplaintCase, error) {
	rows, err := q.db.Query(ctx, listSLADueComplaintCases, arg.TenantID, arg.SlaDueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplaintCase
	for rows.Next() {
		var i ComplaintCase
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InteractionID,
			&i.RedecoCause,
			&i.State,
			&i.OpenedAt,
			&i.SlaDueAt,
			&i.CalendarVersion,
			&i.ReviewExpiresAt,
			&i.ResolvedAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionComplaintCaseToAwaitingReview = `-- name: TransitionComplaintCaseToAwaitingReview :one
UPDATE complaint_cases
SET state = 'awaiting_review', review_expires_at = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND state = 'open'
RETURNING id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
`

type TransitionComplaintCaseToAwaitingReviewParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ID              pgtype.UUID        `json:"id"`
	ReviewExpiresAt pgtype.Timestamptz `json:"review_expires_at"`
}

func (q *Queries) TransitionComplaintCaseToAwaitingReview(ctx context.Context, arg TransitionComplaintCaseToAwaitingReviewParams) (ComplaintCase, error) {
	row := q.db.QueryRow(ctx, transitionComplaintCaseToAwaitingReview, arg.TenantID, arg.ID, arg.ReviewExpiresAt)
	var i ComplaintCase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionID,
		&i.RedecoCause,
		&i.State,
		&i.OpenedAt,
		&i.SlaDueAt,
		&i.CalendarVersion,
		&i.ReviewExpiresAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionComplaintCaseToEscalated = `-- name: TransitionComplaintCaseToEscalated :one
UPDATE complaint_cases
SET state = 'escalated', updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND state = ANY($3::text[])
RETURNING id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
`

type TransitionComplaintCaseToEscalatedParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ID         pgtype.UUID `json:"id"`
	FromStates []string    `json:"from_states"`
}

func (q *Queries) TransitionComplaintCaseToEscalated(ctx context.Context, arg TransitionComplaintCaseToEscalatedParams) (ComplaintCase, error) {
	row := q.db.QueryRow(ctx, transitionComplaintCaseToEscalated, arg.TenantID, arg.ID, arg.FromStates)
	var i ComplaintCase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionID,
		&i.RedecoCause,
		&i.State,
		&i.OpenedAt,
		&i.SlaDueAt,
		&i.CalendarVersion,
		&i.ReviewExpiresAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionComplaintCaseToResolved = `-- name: TransitionComplaintCaseToResolved :one
UPDATE complaint_cases
SET state = 'resolved', resolved_at = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND state = 'awaiting_review' AND review_expires_at > now()
RETURNING id, tenant_id, interaction_id, redeco_cause, state, opened_at, sla_due_at,
    calendar_version, review_expires_at, resolved_at, idempotency_key, created_at, updated_at
`

type TransitionComplaintCaseToResolvedParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ID         pgtype.UUID        `json:"id"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) TransitionComplaintCaseToResolved(ctx context.Context, arg TransitionComplaintCaseToResolvedParams) (ComplaintCase, error) {
	row := q.db.QueryRow(ctx, transitionComplaintCaseToResolved, arg.TenantID, arg.ID, arg.ResolvedAt)
	var i ComplaintCase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionID,
		&i.RedecoCause,
		&i.State,
		&i.OpenedAt,
		&i.SlaDueAt,
		&i.CalendarVersion,
		&i.ReviewExpiresAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
