// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardByCause = `-- name: DashboardByCause :many
SELECT
    detector_code AS rule_code,
    COUNT(*) FILTER (WHERE outcome = 'fail') AS violations,
    COUNT(*) FILTER (WHERE outcome = 'warn') AS warnings
FROM detector_result_rows
GROUP BY detector_code
ORDER BY detector_code ASC
`

type DashboardByCauseRow struct {
	RuleCode   string `json:"rule_code"`
	Violations int64  `json:"violations"`
	Warnings   int64  `json:"warnings"`
}

// Per-REDECO-rule-code breakdown, tenant-scoped implicitly by RLS.
// "violations" counts outcome = 'fail' rows only; "warnings" is a separate
// count of outcome = 'warn' rows (non-zero in practice only for
// MX-REDECO-03) so warn-level activity is visible without inflating
// violations. Both are computed by the same SQL GROUP BY, never fetched and
// counted in application code.
func (q *Queries) DashboardByCause(ctx context.Context) ([]DashboardByCauseRow, error) {
	rows, err := q.db.Query(ctx, dashboardByCause)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardByCauseRow
	for rows.Next() {
		var i DashboardByCauseRow
		if err := rows.Scan(&i.RuleCode, &i.Violations, &i.Warnings); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardByDespacho = `-- name: DashboardByDespacho :many
SELECT despacho_id, despacho_name, total, violations
FROM (
    SELECT
        d.id AS despacho_id,
        COALESCE(d.display_name, 'unattributed') AS despacho_name,
        COUNT(DISTINCT e.interaction_event_id) AS total,
        COUNT(DISTINCT e.interaction_event_id) FILTER (
            WHERE EXISTS (
                SELECT 1 FROM detector_result_rows drr
                WHERE drr.interaction_event_id = e.interaction_event_id
                  AND drr.outcome = 'fail'
            )
        ) AS violations
    FROM evaluations e
    JOIN interaction_events ie ON ie.id = e.interaction_event_id
    LEFT JOIN despachos d ON d.id = ie.despacho_id
    GROUP BY d.id, d.display_name
) agg
ORDER BY
    (violations::numeric / NULLIF(total, 0)) DESC NULLS LAST,
    despacho_name ASC
`

type DashboardByDespachoRow struct {
	DespachoID   pgtype.UUID `json:"despacho_id"`
	DespachoName string      `json:"despacho_name"`
	Total        int64       `json:"total"`
	Violations   int64       `json:"violations"`
}

// Interaction-grain (never detector_result_rows row-grain) violation-rate
// ranking, one evaluation per interaction_event enforced by evaluations'
// UNIQUE(tenant_id, interaction_event_id). Tenant-scoped implicitly by RLS
// (current_setting('app.tenant_id')), like CountOutOfHoursEvaluations --
// no explicit tenant_id filter here. Unattributed interactions
// (interaction_events.despacho_id IS NULL) are reported under an explicit
// synthetic bucket (despacho_id NULL, despacho_name "unattributed") rather
// than silently dropped or folded into a named despacho. "violations" counts
// only rows with outcome = 'fail' (never != 'pass'), so 'review' (judge
// uncertainty) and 'warn' (MX-REDECO-03 confirmed warn-level signal) rows
// are excluded, matching the by-cause endpoint's predicate.
// Wrapped in a derived table so the ORDER BY expression below can reference
// "total"/"violations"/"despacho_name" as real output columns of `agg`:
// referencing an output-list alias (rather than a bare matching identifier)
// inside an arithmetic ORDER BY expression on the original query is resolved
// against the FROM-list instead and fails with "column ... does not exist"
// since no such source column exists.
func (q *Queries) DashboardByDespacho(ctx context.Context) ([]DashboardByDespachoRow, error) {
	rows, err := q.db.Query(ctx, dashboardByDespacho)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardByDespachoRow
	for rows.Next() {
		var i DashboardByDespachoRow
		if err := rows.Scan(
			&i.DespachoID,
			&i.DespachoName,
			&i.Total,
			&i.Violations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
