// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debtors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDebtor = `-- name: CreateDebtor :one
INSERT INTO debtors (tenant_id, external_ref, display_name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, external_ref, display_name, created_at, updated_at
`

type CreateDebtorParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ExternalRef string      `json:"external_ref"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CreateDebtor(ctx context.Context, arg CreateDebtorParams) (Debtor, error) {
	row := q.db.QueryRow(ctx, createDebtor, arg.TenantID, arg.ExternalRef, arg.DisplayName)
	var i Debtor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebtorByTenant = `-- name: GetDebtorByTenant :one
SELECT id, tenant_id, external_ref, display_name, created_at, updated_at
FROM debtors
WHERE tenant_id = $1 AND id = $2
`

type GetDebtorByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetDebtorByTenant(ctx context.Context, arg GetDebtorByTenantParams) (Debtor, error) {
	row := q.db.QueryRow(ctx, getDebtorByTenant, arg.TenantID, arg.ID)
	var i Debtor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDebtorsByTenant = `-- name: ListDebtorsByTenant :many
SELECT id, tenant_id, external_ref, display_name, created_at, updated_at
FROM debtors
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDebtorsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Debtor, error) {
	rows, err := q.db.Query(ctx, listDebtorsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debtor
	for rows.Next() {
		var i Debtor
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
