// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debtors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDebtor = `-- name: CreateDebtor :one
INSERT INTO debtors (tenant_id, external_ref, display_name, timezone, date_of_birth)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, external_ref, display_name, timezone, date_of_birth, created_at, updated_at
`

type CreateDebtorParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ExternalRef string      `json:"external_ref"`
	DisplayName string      `json:"display_name"`
	Timezone    string      `json:"timezone"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
}

type CreateDebtorRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ExternalRef string             `json:"external_ref"`
	DisplayName string             `json:"display_name"`
	Timezone    string             `json:"timezone"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// date_of_birth (issue #7) is the durable DOB source, snapshotted onto
// interaction_events.contacted_party_dob at ingest time by the caller.
func (q *Queries) CreateDebtor(ctx context.Context, arg CreateDebtorParams) (CreateDebtorRow, error) {
	row := q.db.QueryRow(ctx, createDebtor,
		arg.TenantID,
		arg.ExternalRef,
		arg.DisplayName,
		arg.Timezone,
		arg.DateOfBirth,
	)
	var i CreateDebtorRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.DisplayName,
		&i.Timezone,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebtorByTenant = `-- name: GetDebtorByTenant :one
SELECT id, tenant_id, external_ref, display_name, timezone, date_of_birth, created_at, updated_at
FROM debtors
WHERE tenant_id = $1 AND id = $2
`

type GetDebtorByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetDebtorByTenantRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ExternalRef string             `json:"external_ref"`
	DisplayName string             `json:"display_name"`
	Timezone    string             `json:"timezone"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDebtorByTenant(ctx context.Context, arg GetDebtorByTenantParams) (GetDebtorByTenantRow, error) {
	row := q.db.QueryRow(ctx, getDebtorByTenant, arg.TenantID, arg.ID)
	var i GetDebtorByTenantRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.DisplayName,
		&i.Timezone,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDebtorsByTenant = `-- name: ListDebtorsByTenant :many
SELECT id, tenant_id, external_ref, display_name, timezone, date_of_birth, created_at, updated_at
FROM debtors
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListDebtorsByTenantRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ExternalRef string             `json:"external_ref"`
	DisplayName string             `json:"display_name"`
	Timezone    string             `json:"timezone"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDebtorsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListDebtorsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listDebtorsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebtorsByTenantRow
	for rows.Next() {
		var i ListDebtorsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.DisplayName,
			&i.Timezone,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
