// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: despachos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDespacho = `-- name: CreateDespacho :one
INSERT INTO despachos (tenant_id, external_ref, display_name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, external_ref, display_name, created_at, updated_at
`

type CreateDespachoParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ExternalRef string      `json:"external_ref"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CreateDespacho(ctx context.Context, arg CreateDespachoParams) (Despacho, error) {
	row := q.db.QueryRow(ctx, createDespacho, arg.TenantID, arg.ExternalRef, arg.DisplayName)
	var i Despacho
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDespachoByTenant = `-- name: GetDespachoByTenant :one
SELECT id, tenant_id, external_ref, display_name, created_at, updated_at
FROM despachos
WHERE tenant_id = $1 AND id = $2
`

type GetDespachoByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetDespachoByTenant(ctx context.Context, arg GetDespachoByTenantParams) (Despacho, error) {
	row := q.db.QueryRow(ctx, getDespachoByTenant, arg.TenantID, arg.ID)
	var i Despacho
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDespachosByTenant = `-- name: ListDespachosByTenant :many
SELECT id, tenant_id, external_ref, display_name, created_at, updated_at
FROM despachos
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDespachosByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Despacho, error) {
	rows, err := q.db.Query(ctx, listDespachosByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Despacho
	for rows.Next() {
		var i Despacho
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
