// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evaluations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOutOfHoursEvaluations = `-- name: CountOutOfHoursEvaluations :one
SELECT count(*) FROM evaluations WHERE overall_outcome = 'fail'
`

func (q *Queries) CountOutOfHoursEvaluations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOutOfHoursEvaluations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvaluation = `-- name: CreateEvaluation :one
INSERT INTO evaluations (tenant_id, interaction_event_id, overall_outcome)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, interaction_event_id, overall_outcome, policy_bundle_version, created_at
`

type CreateEvaluationParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	InteractionEventID pgtype.UUID `json:"interaction_event_id"`
	OverallOutcome     string      `json:"overall_outcome"`
}

func (q *Queries) CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) (Evaluation, error) {
	row := q.db.QueryRow(ctx, createEvaluation, arg.TenantID, arg.InteractionEventID, arg.OverallOutcome)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionEventID,
		&i.OverallOutcome,
		&i.PolicyBundleVersion,
		&i.CreatedAt,
	)
	return i, err
}
