// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evaluations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOutOfHoursEvaluations = `-- name: CountOutOfHoursEvaluations :one
SELECT count(*) FROM evaluations WHERE overall_outcome = 'fail'
`

func (q *Queries) CountOutOfHoursEvaluations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOutOfHoursEvaluations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvaluation = `-- name: CreateEvaluation :one
INSERT INTO evaluations (tenant_id, interaction_event_id, overall_outcome)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, interaction_event_id, overall_outcome, policy_bundle_version,
    created_at, requires_hitl, judge_model_id, rubric_version
`

type CreateEvaluationParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	InteractionEventID pgtype.UUID `json:"interaction_event_id"`
	OverallOutcome     string      `json:"overall_outcome"`
}

func (q *Queries) CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) (Evaluation, error) {
	row := q.db.QueryRow(ctx, createEvaluation, arg.TenantID, arg.InteractionEventID, arg.OverallOutcome)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionEventID,
		&i.OverallOutcome,
		&i.PolicyBundleVersion,
		&i.CreatedAt,
		&i.RequiresHitl,
		&i.JudgeModelID,
		&i.RubricVersion,
	)
	return i, err
}

const getEvaluationByInteractionEventID = `-- name: GetEvaluationByInteractionEventID :one
SELECT id, tenant_id, interaction_event_id, overall_outcome, policy_bundle_version,
    created_at, requires_hitl, judge_model_id, rubric_version
FROM evaluations
WHERE tenant_id = $1 AND interaction_event_id = $2
`

type GetEvaluationByInteractionEventIDParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	InteractionEventID pgtype.UUID `json:"interaction_event_id"`
}

// Used by cmd/seed to detect whether a pre-existing (re-run) interaction
// still needs to be backfilled with an evaluation.
func (q *Queries) GetEvaluationByInteractionEventID(ctx context.Context, arg GetEvaluationByInteractionEventIDParams) (Evaluation, error) {
	row := q.db.QueryRow(ctx, getEvaluationByInteractionEventID, arg.TenantID, arg.InteractionEventID)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionEventID,
		&i.OverallOutcome,
		&i.PolicyBundleVersion,
		&i.CreatedAt,
		&i.RequiresHitl,
		&i.JudgeModelID,
		&i.RubricVersion,
	)
	return i, err
}
