// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evidence_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEvidenceRecordByInteraction = `-- name: GetEvidenceRecordByInteraction :one
SELECT id, tenant_id, interaction_event_id, evaluation_id, seq, prev_hash, hash,
    overall_outcome, policy_bundle_version, inputs_digest, created_at,
    judge_rubric_version, judge_model_id, judge_confidence, record_kind,
    complaint_case_id, transition_kind, transition_from_state, transition_to_state, human_review_id
FROM evidence_records WHERE tenant_id = $1 AND interaction_event_id = $2
`

type GetEvidenceRecordByInteractionParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	InteractionEventID pgtype.UUID `json:"interaction_event_id"`
}

// Export endpoint lookup.
func (q *Queries) GetEvidenceRecordByInteraction(ctx context.Context, arg GetEvidenceRecordByInteractionParams) (EvidenceRecord, error) {
	row := q.db.QueryRow(ctx, getEvidenceRecordByInteraction, arg.TenantID, arg.InteractionEventID)
	var i EvidenceRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionEventID,
		&i.EvaluationID,
		&i.Seq,
		&i.PrevHash,
		&i.Hash,
		&i.OverallOutcome,
		&i.PolicyBundleVersion,
		&i.InputsDigest,
		&i.CreatedAt,
		&i.JudgeRubricVersion,
		&i.JudgeModelID,
		&i.JudgeConfidence,
		&i.RecordKind,
		&i.ComplaintCaseID,
		&i.TransitionKind,
		&i.TransitionFromState,
		&i.TransitionToState,
		&i.HumanReviewID,
	)
	return i, err
}

const insertComplaintTransitionEvidenceRecord = `-- name: InsertComplaintTransitionEvidenceRecord :one
INSERT INTO evidence_records (tenant_id, interaction_event_id, evaluation_id, seq,
    prev_hash, hash, overall_outcome, policy_bundle_version, inputs_digest, created_at,
    record_kind, complaint_case_id, transition_kind, transition_from_state, transition_to_state,
    human_review_id)
VALUES ($1,NULL,NULL,$2,$3,$4,$5,'',$6,$7,'complaint_transition',$8,$9,$10,$11,$12)
RETURNING id, tenant_id, interaction_event_id, evaluation_id, seq, prev_hash, hash,
    overall_outcome, policy_bundle_version, inputs_digest, created_at,
    judge_rubric_version, judge_model_id, judge_confidence, record_kind,
    complaint_case_id, transition_kind, transition_from_state, transition_to_state, human_review_id
`

type InsertComplaintTransitionEvidenceRecordParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Seq                 int64              `json:"seq"`
	PrevHash            string             `json:"prev_hash"`
	Hash                string             `json:"hash"`
	OverallOutcome      string             `json:"overall_outcome"`
	InputsDigest        string             `json:"inputs_digest"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ComplaintCaseID     pgtype.UUID        `json:"complaint_case_id"`
	TransitionKind      *string            `json:"transition_kind"`
	TransitionFromState *string            `json:"transition_from_state"`
	TransitionToState   *string            `json:"transition_to_state"`
	HumanReviewID       pgtype.UUID        `json:"human_review_id"`
}

func (q *Queries) InsertComplaintTransitionEvidenceRecord(ctx context.Context, arg InsertComplaintTransitionEvidenceRecordParams) (EvidenceRecord, error) {
	row := q.db.QueryRow(ctx, insertComplaintTransitionEvidenceRecord,
		arg.TenantID,
		arg.Seq,
		arg.PrevHash,
		arg.Hash,
		arg.OverallOutcome,
		arg.InputsDigest,
		arg.CreatedAt,
		arg.ComplaintCaseID,
		arg.TransitionKind,
		arg.TransitionFromState,
		arg.TransitionToState,
		arg.HumanReviewID,
	)
	var i EvidenceRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionEventID,
		&i.EvaluationID,
		&i.Seq,
		&i.PrevHash,
		&i.Hash,
		&i.OverallOutcome,
		&i.PolicyBundleVersion,
		&i.InputsDigest,
		&i.CreatedAt,
		&i.JudgeRubricVersion,
		&i.JudgeModelID,
		&i.JudgeConfidence,
		&i.RecordKind,
		&i.ComplaintCaseID,
		&i.TransitionKind,
		&i.TransitionFromState,
		&i.TransitionToState,
		&i.HumanReviewID,
	)
	return i, err
}

const insertEvidenceRecord = `-- name: InsertEvidenceRecord :one
INSERT INTO evidence_records (tenant_id, interaction_event_id, evaluation_id, seq,
    prev_hash, hash, overall_outcome, policy_bundle_version, inputs_digest, created_at,
    judge_rubric_version, judge_model_id, judge_confidence, record_kind)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'evaluation')
RETURNING id, tenant_id, interaction_event_id, evaluation_id, seq, prev_hash, hash,
    overall_outcome, policy_bundle_version, inputs_digest, created_at,
    judge_rubric_version, judge_model_id, judge_confidence, record_kind,
    complaint_case_id, transition_kind, transition_from_state, transition_to_state, human_review_id
`

type InsertEvidenceRecordParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	InteractionEventID  pgtype.UUID        `json:"interaction_event_id"`
	EvaluationID        pgtype.UUID        `json:"evaluation_id"`
	Seq                 int64              `json:"seq"`
	PrevHash            string             `json:"prev_hash"`
	Hash                string             `json:"hash"`
	OverallOutcome      string             `json:"overall_outcome"`
	PolicyBundleVersion string             `json:"policy_bundle_version"`
	InputsDigest        string             `json:"inputs_digest"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	JudgeRubricVersion  *string            `json:"judge_rubric_version"`
	JudgeModelID        *string            `json:"judge_model_id"`
	JudgeConfidence     *string            `json:"judge_confidence"`
}

func (q *Queries) InsertEvidenceRecord(ctx context.Context, arg InsertEvidenceRecordParams) (EvidenceRecord, error) {
	row := q.db.QueryRow(ctx, insertEvidenceRecord,
		arg.TenantID,
		arg.InteractionEventID,
		arg.EvaluationID,
		arg.Seq,
		arg.PrevHash,
		arg.Hash,
		arg.OverallOutcome,
		arg.PolicyBundleVersion,
		arg.InputsDigest,
		arg.CreatedAt,
		arg.JudgeRubricVersion,
		arg.JudgeModelID,
		arg.JudgeConfidence,
	)
	var i EvidenceRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionEventID,
		&i.EvaluationID,
		&i.Seq,
		&i.PrevHash,
		&i.Hash,
		&i.OverallOutcome,
		&i.PolicyBundleVersion,
		&i.InputsDigest,
		&i.CreatedAt,
		&i.JudgeRubricVersion,
		&i.JudgeModelID,
		&i.JudgeConfidence,
		&i.RecordKind,
		&i.ComplaintCaseID,
		&i.TransitionKind,
		&i.TransitionFromState,
		&i.TransitionToState,
		&i.HumanReviewID,
	)
	return i, err
}

const listDetectorResultRowsByEvaluation = `-- name: ListDetectorResultRowsByEvaluation :many
SELECT detector_code, outcome, severity, result_payload
FROM detector_result_rows WHERE evaluation_id = $1 ORDER BY detector_code ASC
`

type ListDetectorResultRowsByEvaluationRow struct {
	DetectorCode  string `json:"detector_code"`
	Outcome       string `json:"outcome"`
	Severity      string `json:"severity"`
	ResultPayload []byte `json:"result_payload"`
}

// Package detector layer for evidence export, sorted by detector_code.
func (q *Queries) ListDetectorResultRowsByEvaluation(ctx context.Context, evaluationID pgtype.UUID) ([]ListDetectorResultRowsByEvaluationRow, error) {
	rows, err := q.db.Query(ctx, listDetectorResultRowsByEvaluation, evaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDetectorResultRowsByEvaluationRow
	for rows.Next() {
		var i ListDetectorResultRowsByEvaluationRow
		if err := rows.Scan(
			&i.DetectorCode,
			&i.Outcome,
			&i.Severity,
			&i.ResultPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceRecordsByTenant = `-- name: ListEvidenceRecordsByTenant :many
SELECT id, tenant_id, interaction_event_id, evaluation_id, seq, prev_hash, hash,
    overall_outcome, policy_bundle_version, inputs_digest, created_at,
    judge_rubric_version, judge_model_id, judge_confidence, record_kind,
    complaint_case_id, transition_kind, transition_from_state, transition_to_state, human_review_id
FROM evidence_records WHERE tenant_id = $1 ORDER BY seq ASC
`

// Store-backed VerifyChain: replay a tenant's chain ordered by seq.
func (q *Queries) ListEvidenceRecordsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]EvidenceRecord, error) {
	rows, err := q.db.Query(ctx, listEvidenceRecordsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceRecord
	for rows.Next() {
		var i EvidenceRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InteractionEventID,
			&i.EvaluationID,
			&i.Seq,
			&i.PrevHash,
			&i.Hash,
			&i.OverallOutcome,
			&i.PolicyBundleVersion,
			&i.InputsDigest,
			&i.CreatedAt,
			&i.JudgeRubricVersion,
			&i.JudgeModelID,
			&i.JudgeConfidence,
			&i.RecordKind,
			&i.ComplaintCaseID,
			&i.TransitionKind,
			&i.TransitionFromState,
			&i.TransitionToState,
			&i.HumanReviewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
