// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: human_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnprocessedHumanReviewForCase = `-- name: GetUnprocessedHumanReviewForCase :one
SELECT id, tenant_id, complaint_case_id, decision, reviewer, notes,
    processed_at, superseded_at, created_at, updated_at
FROM human_reviews
WHERE tenant_id = $1
  AND complaint_case_id = $2
  AND id = $3
  AND decision = $4
  AND processed_at IS NULL
  AND superseded_at IS NULL
`

type GetUnprocessedHumanReviewForCaseParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	ComplaintCaseID pgtype.UUID `json:"complaint_case_id"`
	ID              pgtype.UUID `json:"id"`
	Decision        string      `json:"decision"`
}

func (q *Queries) GetUnprocessedHumanReviewForCase(ctx context.Context, arg GetUnprocessedHumanReviewForCaseParams) (HumanReview, error) {
	row := q.db.QueryRow(ctx, getUnprocessedHumanReviewForCase,
		arg.TenantID,
		arg.ComplaintCaseID,
		arg.ID,
		arg.Decision,
	)
	var i HumanReview
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ComplaintCaseID,
		&i.Decision,
		&i.Reviewer,
		&i.Notes,
		&i.ProcessedAt,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHumanReview = `-- name: InsertHumanReview :one
INSERT INTO human_reviews (tenant_id, complaint_case_id, decision, reviewer, notes)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (
    SELECT 1 FROM complaint_cases
    WHERE tenant_id = $1 AND id = $2 AND state = 'awaiting_review'
)
RETURNING id, tenant_id, complaint_case_id, decision, reviewer, notes,
    processed_at, superseded_at, created_at, updated_at
`

type InsertHumanReviewParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	ComplaintCaseID pgtype.UUID `json:"complaint_case_id"`
	Decision        string      `json:"decision"`
	Reviewer        string      `json:"reviewer"`
	Notes           string      `json:"notes"`
}

func (q *Queries) InsertHumanReview(ctx context.Context, arg InsertHumanReviewParams) (HumanReview, error) {
	row := q.db.QueryRow(ctx, insertHumanReview,
		arg.TenantID,
		arg.ComplaintCaseID,
		arg.Decision,
		arg.Reviewer,
		arg.Notes,
	)
	var i HumanReview
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ComplaintCaseID,
		&i.Decision,
		&i.Reviewer,
		&i.Notes,
		&i.ProcessedAt,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnprocessedHumanReviews = `-- name: ListUnprocessedHumanReviews :many
SELECT hr.id, hr.tenant_id, hr.complaint_case_id, hr.decision, hr.reviewer, hr.notes,
    hr.processed_at, hr.superseded_at, hr.created_at, hr.updated_at
FROM human_reviews hr
JOIN complaint_cases cc ON cc.id = hr.complaint_case_id AND cc.tenant_id = hr.tenant_id
WHERE hr.tenant_id = $1
  AND cc.state = 'awaiting_review'
  AND hr.processed_at IS NULL
  AND hr.superseded_at IS NULL
ORDER BY hr.created_at ASC
LIMIT $2
`

type ListUnprocessedHumanReviewsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListUnprocessedHumanReviews(ctx context.Context, arg ListUnprocessedHumanReviewsParams) ([]HumanReview, error) {
	rows, err := q.db.Query(ctx, listUnprocessedHumanReviews, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HumanReview
	for rows.Next() {
		var i HumanReview
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ComplaintCaseID,
			&i.Decision,
			&i.Reviewer,
			&i.Notes,
			&i.ProcessedAt,
			&i.SupersededAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOtherHumanReviewsSuperseded = `-- name: MarkOtherHumanReviewsSuperseded :execrows
UPDATE human_reviews
SET superseded_at = $4, updated_at = now()
WHERE tenant_id = $1
  AND complaint_case_id = $2
  AND id <> $3
  AND processed_at IS NULL
  AND superseded_at IS NULL
`

type MarkOtherHumanReviewsSupersededParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ComplaintCaseID pgtype.UUID        `json:"complaint_case_id"`
	ID              pgtype.UUID        `json:"id"`
	SupersededAt    pgtype.Timestamptz `json:"superseded_at"`
}

func (q *Queries) MarkOtherHumanReviewsSuperseded(ctx context.Context, arg MarkOtherHumanReviewsSupersededParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOtherHumanReviewsSuperseded,
		arg.TenantID,
		arg.ComplaintCaseID,
		arg.ID,
		arg.SupersededAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWinningHumanReviewProcessed = `-- name: MarkWinningHumanReviewProcessed :one
UPDATE human_reviews
SET processed_at = $4, updated_at = now()
WHERE tenant_id = $1
  AND complaint_case_id = $2
  AND id = $3
  AND processed_at IS NULL
  AND superseded_at IS NULL
RETURNING id, tenant_id, complaint_case_id, decision, reviewer, notes,
    processed_at, superseded_at, created_at, updated_at
`

type MarkWinningHumanReviewProcessedParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ComplaintCaseID pgtype.UUID        `json:"complaint_case_id"`
	ID              pgtype.UUID        `json:"id"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) MarkWinningHumanReviewProcessed(ctx context.Context, arg MarkWinningHumanReviewProcessedParams) (HumanReview, error) {
	row := q.db.QueryRow(ctx, markWinningHumanReviewProcessed,
		arg.TenantID,
		arg.ComplaintCaseID,
		arg.ID,
		arg.ProcessedAt,
	)
	var i HumanReview
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ComplaintCaseID,
		&i.Decision,
		&i.Reviewer,
		&i.Notes,
		&i.ProcessedAt,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
