// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interaction_transcripts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInteractionTranscript = `-- name: CreateInteractionTranscript :one
INSERT INTO interaction_transcripts (tenant_id, interaction_event_id, utterances)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, interaction_event_id, utterances, created_at
`

type CreateInteractionTranscriptParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	InteractionEventID pgtype.UUID `json:"interaction_event_id"`
	Utterances         []byte      `json:"utterances"`
}

func (q *Queries) CreateInteractionTranscript(ctx context.Context, arg CreateInteractionTranscriptParams) (InteractionTranscript, error) {
	row := q.db.QueryRow(ctx, createInteractionTranscript, arg.TenantID, arg.InteractionEventID, arg.Utterances)
	var i InteractionTranscript
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionEventID,
		&i.Utterances,
		&i.CreatedAt,
	)
	return i, err
}

const getInteractionTranscriptByInteraction = `-- name: GetInteractionTranscriptByInteraction :one
SELECT id, tenant_id, interaction_event_id, utterances, created_at
FROM interaction_transcripts
WHERE tenant_id = $1 AND interaction_event_id = $2
`

type GetInteractionTranscriptByInteractionParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	InteractionEventID pgtype.UUID `json:"interaction_event_id"`
}

func (q *Queries) GetInteractionTranscriptByInteraction(ctx context.Context, arg GetInteractionTranscriptByInteractionParams) (InteractionTranscript, error) {
	row := q.db.QueryRow(ctx, getInteractionTranscriptByInteraction, arg.TenantID, arg.InteractionEventID)
	var i InteractionTranscript
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InteractionEventID,
		&i.Utterances,
		&i.CreatedAt,
	)
	return i, err
}
