// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interaction_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInteractionEvent = `-- name: CreateInteractionEvent :one
INSERT INTO interaction_events (tenant_id, debtor_id, channel, direction, status, occurred_at, transcript_ref, debtor_timezone)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, debtor_id, channel, direction, status, occurred_at, transcript_ref, debtor_timezone, created_at
`

type CreateInteractionEventParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DebtorID       pgtype.UUID        `json:"debtor_id"`
	Channel        string             `json:"channel"`
	Direction      string             `json:"direction"`
	Status         string             `json:"status"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef  *string            `json:"transcript_ref"`
	DebtorTimezone string             `json:"debtor_timezone"`
}

type CreateInteractionEventRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DebtorID       pgtype.UUID        `json:"debtor_id"`
	Channel        string             `json:"channel"`
	Direction      string             `json:"direction"`
	Status         string             `json:"status"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef  *string            `json:"transcript_ref"`
	DebtorTimezone string             `json:"debtor_timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateInteractionEvent(ctx context.Context, arg CreateInteractionEventParams) (CreateInteractionEventRow, error) {
	row := q.db.QueryRow(ctx, createInteractionEvent,
		arg.TenantID,
		arg.DebtorID,
		arg.Channel,
		arg.Direction,
		arg.Status,
		arg.OccurredAt,
		arg.TranscriptRef,
		arg.DebtorTimezone,
	)
	var i CreateInteractionEventRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DebtorID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.OccurredAt,
		&i.TranscriptRef,
		&i.DebtorTimezone,
		&i.CreatedAt,
	)
	return i, err
}

const getInteractionEventByID = `-- name: GetInteractionEventByID :one
SELECT id, tenant_id, debtor_id, channel, direction, status, occurred_at, transcript_ref, debtor_timezone, created_at
FROM interaction_events
WHERE id = $1 AND tenant_id = $2
`

type GetInteractionEventByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetInteractionEventByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DebtorID       pgtype.UUID        `json:"debtor_id"`
	Channel        string             `json:"channel"`
	Direction      string             `json:"direction"`
	Status         string             `json:"status"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef  *string            `json:"transcript_ref"`
	DebtorTimezone string             `json:"debtor_timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Evidence export lookup (issue #3): fetch a single interaction scoped to
// its tenant.
func (q *Queries) GetInteractionEventByID(ctx context.Context, arg GetInteractionEventByIDParams) (GetInteractionEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getInteractionEventByID, arg.ID, arg.TenantID)
	var i GetInteractionEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DebtorID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.OccurredAt,
		&i.TranscriptRef,
		&i.DebtorTimezone,
		&i.CreatedAt,
	)
	return i, err
}

const listCurrentTenantInteractions = `-- name: ListCurrentTenantInteractions :many
SELECT id, tenant_id, debtor_id, channel, direction, status, occurred_at, transcript_ref, debtor_timezone, created_at
FROM interaction_events
ORDER BY occurred_at DESC
LIMIT $1
`

type ListCurrentTenantInteractionsRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DebtorID       pgtype.UUID        `json:"debtor_id"`
	Channel        string             `json:"channel"`
	Direction      string             `json:"direction"`
	Status         string             `json:"status"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef  *string            `json:"transcript_ref"`
	DebtorTimezone string             `json:"debtor_timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListCurrentTenantInteractions(ctx context.Context, limit int32) ([]ListCurrentTenantInteractionsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentTenantInteractions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentTenantInteractionsRow
	for rows.Next() {
		var i ListCurrentTenantInteractionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DebtorID,
			&i.Channel,
			&i.Direction,
			&i.Status,
			&i.OccurredAt,
			&i.TranscriptRef,
			&i.DebtorTimezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentTenantInteractionsWithOutcome = `-- name: ListCurrentTenantInteractionsWithOutcome :many
SELECT
    ie.id, ie.tenant_id, ie.debtor_id, ie.channel, ie.direction, ie.status,
    ie.occurred_at, ie.transcript_ref, ie.debtor_timezone, ie.created_at,
    e.overall_outcome,
    e.requires_hitl,
    CASE WHEN e.id IS NULL THEN NULL ELSE agg.threat_flagged END AS threat_flagged,
    agg.reason
FROM interaction_events ie
LEFT JOIN evaluations e ON e.interaction_event_id = ie.id
LEFT JOIN LATERAL (
    SELECT
        bool_or(dr.detector_code = 'MX-REDECO-05' AND dr.outcome IN ('fail', 'review'))
            AS threat_flagged,
        (array_agg(
            dr.result_payload ->> 'rationale'
            ORDER BY
                CASE dr.severity
                    WHEN 'critical' THEN 4 WHEN 'high' THEN 3
                    WHEN 'medium'  THEN 2 WHEN 'low'   THEN 1 ELSE 0 END DESC,
                dr.detector_code ASC
        ))[1] AS reason
    FROM detector_result_rows dr
    WHERE dr.evaluation_id = e.id
) agg ON true
ORDER BY ie.occurred_at DESC
LIMIT $1
`

type ListCurrentTenantInteractionsWithOutcomeRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DebtorID       pgtype.UUID        `json:"debtor_id"`
	Channel        string             `json:"channel"`
	Direction      string             `json:"direction"`
	Status         string             `json:"status"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef  *string            `json:"transcript_ref"`
	DebtorTimezone string             `json:"debtor_timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	OverallOutcome *string            `json:"overall_outcome"`
	RequiresHitl   *bool              `json:"requires_hitl"`
	ThreatFlagged  interface{}        `json:"threat_flagged"`
	Reason         interface{}        `json:"reason"`
}

// Issue #4 rewrite: aggregates across detector_result_rows per evaluation
// (worst-severity-wins for the displayed reason, bool_or threat_flagged for
// MX-REDECO-05) instead of assuming at most one detector result per
// evaluation. One row per interaction — the LATERAL subquery collapses
// every detector_result_rows child before the join, so a second
// detector/judge result never fans out the interaction row.
func (q *Queries) ListCurrentTenantInteractionsWithOutcome(ctx context.Context, limit int32) ([]ListCurrentTenantInteractionsWithOutcomeRow, error) {
	rows, err := q.db.Query(ctx, listCurrentTenantInteractionsWithOutcome, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentTenantInteractionsWithOutcomeRow
	for rows.Next() {
		var i ListCurrentTenantInteractionsWithOutcomeRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DebtorID,
			&i.Channel,
			&i.Direction,
			&i.Status,
			&i.OccurredAt,
			&i.TranscriptRef,
			&i.DebtorTimezone,
			&i.CreatedAt,
			&i.OverallOutcome,
			&i.RequiresHitl,
			&i.ThreatFlagged,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInteractionEventsByTenant = `-- name: ListInteractionEventsByTenant :many
SELECT id, tenant_id, debtor_id, channel, direction, status, occurred_at, transcript_ref, debtor_timezone, created_at
FROM interaction_events
WHERE tenant_id = $1
ORDER BY occurred_at DESC
`

type ListInteractionEventsByTenantRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DebtorID       pgtype.UUID        `json:"debtor_id"`
	Channel        string             `json:"channel"`
	Direction      string             `json:"direction"`
	Status         string             `json:"status"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef  *string            `json:"transcript_ref"`
	DebtorTimezone string             `json:"debtor_timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListInteractionEventsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListInteractionEventsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listInteractionEventsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInteractionEventsByTenantRow
	for rows.Next() {
		var i ListInteractionEventsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DebtorID,
			&i.Channel,
			&i.Direction,
			&i.Status,
			&i.OccurredAt,
			&i.TranscriptRef,
			&i.DebtorTimezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
