// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interaction_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInteractionEvent = `-- name: CreateInteractionEvent :one
INSERT INTO interaction_events (tenant_id, debtor_id, channel, direction, status, occurred_at, transcript_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, debtor_id, channel, direction, status, occurred_at, transcript_ref, created_at
`

type CreateInteractionEventParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	DebtorID      pgtype.UUID        `json:"debtor_id"`
	Channel       string             `json:"channel"`
	Direction     string             `json:"direction"`
	Status        string             `json:"status"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef *string            `json:"transcript_ref"`
}

func (q *Queries) CreateInteractionEvent(ctx context.Context, arg CreateInteractionEventParams) (InteractionEvent, error) {
	row := q.db.QueryRow(ctx, createInteractionEvent,
		arg.TenantID,
		arg.DebtorID,
		arg.Channel,
		arg.Direction,
		arg.Status,
		arg.OccurredAt,
		arg.TranscriptRef,
	)
	var i InteractionEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DebtorID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.OccurredAt,
		&i.TranscriptRef,
		&i.CreatedAt,
	)
	return i, err
}

const listInteractionEventsByTenant = `-- name: ListInteractionEventsByTenant :many
SELECT id, tenant_id, debtor_id, channel, direction, status, occurred_at, transcript_ref, created_at
FROM interaction_events
WHERE tenant_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListInteractionEventsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]InteractionEvent, error) {
	rows, err := q.db.Query(ctx, listInteractionEventsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InteractionEvent
	for rows.Next() {
		var i InteractionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DebtorID,
			&i.Channel,
			&i.Direction,
			&i.Status,
			&i.OccurredAt,
			&i.TranscriptRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
