// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_chain_heads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockChainHead = `-- name: LockChainHead :one
INSERT INTO ledger_chain_heads (tenant_id, last_seq, last_hash)
VALUES ($1, 0, $2)                       -- $2 = GenesisPrevHash
ON CONFLICT (tenant_id)
DO UPDATE SET last_seq = ledger_chain_heads.last_seq
RETURNING last_seq, last_hash
`

type LockChainHeadParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	LastHash string      `json:"last_hash"`
}

type LockChainHeadRow struct {
	LastSeq  int64  `json:"last_seq"`
	LastHash string `json:"last_hash"`
}

// Insert-or-lock: first append inserts the genesis head; later appends take the
// row lock via the no-op self-update. Either way returns the locked head.
func (q *Queries) LockChainHead(ctx context.Context, arg LockChainHeadParams) (LockChainHeadRow, error) {
	row := q.db.QueryRow(ctx, lockChainHead, arg.TenantID, arg.LastHash)
	var i LockChainHeadRow
	err := row.Scan(&i.LastSeq, &i.LastHash)
	return i, err
}

const updateChainHead = `-- name: UpdateChainHead :exec
UPDATE ledger_chain_heads SET last_seq = $2, last_hash = $3 WHERE tenant_id = $1
`

type UpdateChainHeadParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	LastSeq  int64       `json:"last_seq"`
	LastHash string      `json:"last_hash"`
}

func (q *Queries) UpdateChainHead(ctx context.Context, arg UpdateChainHeadParams) error {
	_, err := q.db.Exec(ctx, updateChainHead, arg.TenantID, arg.LastSeq, arg.LastHash)
	return err
}
