// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merkle_checkpoints.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMerkleCheckpoint = `-- name: InsertMerkleCheckpoint :one
INSERT INTO merkle_checkpoints (tenant_id, first_seq, last_seq, record_count,
    root_hash, chain_head_hash, checkpoint_body, rfc3161_token, tsa_url, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, first_seq, last_seq, record_count, root_hash,
    chain_head_hash, checkpoint_body, rfc3161_token, tsa_url, created_at
`

type InsertMerkleCheckpointParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	FirstSeq       int64              `json:"first_seq"`
	LastSeq        int64              `json:"last_seq"`
	RecordCount    int64              `json:"record_count"`
	RootHash       string             `json:"root_hash"`
	ChainHeadHash  string             `json:"chain_head_hash"`
	CheckpointBody []byte             `json:"checkpoint_body"`
	Rfc3161Token   []byte             `json:"rfc3161_token"`
	TsaUrl         string             `json:"tsa_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertMerkleCheckpoint(ctx context.Context, arg InsertMerkleCheckpointParams) (MerkleCheckpoint, error) {
	row := q.db.QueryRow(ctx, insertMerkleCheckpoint,
		arg.TenantID,
		arg.FirstSeq,
		arg.LastSeq,
		arg.RecordCount,
		arg.RootHash,
		arg.ChainHeadHash,
		arg.CheckpointBody,
		arg.Rfc3161Token,
		arg.TsaUrl,
		arg.CreatedAt,
	)
	var i MerkleCheckpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstSeq,
		&i.LastSeq,
		&i.RecordCount,
		&i.RootHash,
		&i.ChainHeadHash,
		&i.CheckpointBody,
		&i.Rfc3161Token,
		&i.TsaUrl,
		&i.CreatedAt,
	)
	return i, err
}

const latestMerkleCheckpoint = `-- name: LatestMerkleCheckpoint :one
SELECT id, tenant_id, first_seq, last_seq, record_count, root_hash,
    chain_head_hash, checkpoint_body, rfc3161_token, tsa_url, created_at
FROM merkle_checkpoints
WHERE tenant_id = $1
ORDER BY last_seq DESC
LIMIT 1
`

func (q *Queries) LatestMerkleCheckpoint(ctx context.Context, tenantID pgtype.UUID) (MerkleCheckpoint, error) {
	row := q.db.QueryRow(ctx, latestMerkleCheckpoint, tenantID)
	var i MerkleCheckpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstSeq,
		&i.LastSeq,
		&i.RecordCount,
		&i.RootHash,
		&i.ChainHeadHash,
		&i.CheckpointBody,
		&i.Rfc3161Token,
		&i.TsaUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listEvidenceRecordsByTenantAfterSeq = `-- name: ListEvidenceRecordsByTenantAfterSeq :many
SELECT id, tenant_id, interaction_event_id, evaluation_id, seq, prev_hash, hash,
    overall_outcome, policy_bundle_version, inputs_digest, created_at,
    judge_rubric_version, judge_model_id, judge_confidence, record_kind,
    complaint_case_id, transition_kind, transition_from_state,
    transition_to_state, human_review_id
FROM evidence_records
WHERE tenant_id = $1 AND seq > $2
ORDER BY seq ASC
`

type ListEvidenceRecordsByTenantAfterSeqParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Seq      int64       `json:"seq"`
}

func (q *Queries) ListEvidenceRecordsByTenantAfterSeq(ctx context.Context, arg ListEvidenceRecordsByTenantAfterSeqParams) ([]EvidenceRecord, error) {
	rows, err := q.db.Query(ctx, listEvidenceRecordsByTenantAfterSeq, arg.TenantID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceRecord
	for rows.Next() {
		var i EvidenceRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InteractionEventID,
			&i.EvaluationID,
			&i.Seq,
			&i.PrevHash,
			&i.Hash,
			&i.OverallOutcome,
			&i.PolicyBundleVersion,
			&i.InputsDigest,
			&i.CreatedAt,
			&i.JudgeRubricVersion,
			&i.JudgeModelID,
			&i.JudgeConfidence,
			&i.RecordKind,
			&i.ComplaintCaseID,
			&i.TransitionKind,
			&i.TransitionFromState,
			&i.TransitionToState,
			&i.HumanReviewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceRecordsByTenantSeqRange = `-- name: ListEvidenceRecordsByTenantSeqRange :many
SELECT id, tenant_id, interaction_event_id, evaluation_id, seq, prev_hash, hash,
    overall_outcome, policy_bundle_version, inputs_digest, created_at,
    judge_rubric_version, judge_model_id, judge_confidence, record_kind,
    complaint_case_id, transition_kind, transition_from_state,
    transition_to_state, human_review_id
FROM evidence_records
WHERE tenant_id = $1 AND seq >= $2 AND seq <= $3
ORDER BY seq ASC
`

type ListEvidenceRecordsByTenantSeqRangeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Seq      int64       `json:"seq"`
	Seq_2    int64       `json:"seq_2"`
}

func (q *Queries) ListEvidenceRecordsByTenantSeqRange(ctx context.Context, arg ListEvidenceRecordsByTenantSeqRangeParams) ([]EvidenceRecord, error) {
	rows, err := q.db.Query(ctx, listEvidenceRecordsByTenantSeqRange, arg.TenantID, arg.Seq, arg.Seq_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceRecord
	for rows.Next() {
		var i EvidenceRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InteractionEventID,
			&i.EvaluationID,
			&i.Seq,
			&i.PrevHash,
			&i.Hash,
			&i.OverallOutcome,
			&i.PolicyBundleVersion,
			&i.InputsDigest,
			&i.CreatedAt,
			&i.JudgeRubricVersion,
			&i.JudgeModelID,
			&i.JudgeConfidence,
			&i.RecordKind,
			&i.ComplaintCaseID,
			&i.TransitionKind,
			&i.TransitionFromState,
			&i.TransitionToState,
			&i.HumanReviewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerkleCheckpointsByTenant = `-- name: ListMerkleCheckpointsByTenant :many
SELECT id, tenant_id, first_seq, last_seq, record_count, root_hash,
    chain_head_hash, checkpoint_body, rfc3161_token, tsa_url, created_at
FROM merkle_checkpoints
WHERE tenant_id = $1
ORDER BY last_seq ASC
`

func (q *Queries) ListMerkleCheckpointsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]MerkleCheckpoint, error) {
	rows, err := q.db.Query(ctx, listMerkleCheckpointsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MerkleCheckpoint
	for rows.Next() {
		var i MerkleCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FirstSeq,
			&i.LastSeq,
			&i.RecordCount,
			&i.RootHash,
			&i.ChainHeadHash,
			&i.CheckpointBody,
			&i.Rfc3161Token,
			&i.TsaUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
