// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Debtor struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ExternalRef string             `json:"external_ref"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DetectorResultRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	InteractionEventID pgtype.UUID        `json:"interaction_event_id"`
	DetectorCode       string             `json:"detector_code"`
	Outcome            string             `json:"outcome"`
	Severity           string             `json:"severity"`
	ResultPayload      []byte             `json:"result_payload"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type InteractionEvent struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	DebtorID      pgtype.UUID        `json:"debtor_id"`
	Channel       string             `json:"channel"`
	Direction     string             `json:"direction"`
	Status        string             `json:"status"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef *string            `json:"transcript_ref"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PolicyBundle struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Version   string             `json:"version"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PolicyBundleRule struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	PolicyBundleID pgtype.UUID        `json:"policy_bundle_id"`
	PolicyRuleID   pgtype.UUID        `json:"policy_rule_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PolicyRule struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Severity    string             `json:"severity"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TenantApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	KeyHash    string             `json:"key_hash"`
	Label      string             `json:"label"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}
