// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState `json:"river_job_state"`
	Valid         bool          `json:"valid"` // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Debtor struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ExternalRef string             `json:"external_ref"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Timezone    string             `json:"timezone"`
}

type DetectorResultRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	InteractionEventID pgtype.UUID        `json:"interaction_event_id"`
	DetectorCode       string             `json:"detector_code"`
	Outcome            string             `json:"outcome"`
	Severity           string             `json:"severity"`
	ResultPayload      []byte             `json:"result_payload"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EvaluationID       pgtype.UUID        `json:"evaluation_id"`
}

type Evaluation struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	InteractionEventID  pgtype.UUID        `json:"interaction_event_id"`
	OverallOutcome      string             `json:"overall_outcome"`
	PolicyBundleVersion string             `json:"policy_bundle_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type EvidenceRecord struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	InteractionEventID  pgtype.UUID        `json:"interaction_event_id"`
	EvaluationID        pgtype.UUID        `json:"evaluation_id"`
	Seq                 int64              `json:"seq"`
	PrevHash            string             `json:"prev_hash"`
	Hash                string             `json:"hash"`
	OverallOutcome      string             `json:"overall_outcome"`
	PolicyBundleVersion string             `json:"policy_bundle_version"`
	InputsDigest        string             `json:"inputs_digest"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type InteractionEvent struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DebtorID       pgtype.UUID        `json:"debtor_id"`
	Channel        string             `json:"channel"`
	Direction      string             `json:"direction"`
	Status         string             `json:"status"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	TranscriptRef  *string            `json:"transcript_ref"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DebtorTimezone string             `json:"debtor_timezone"`
}

type LedgerChainHead struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	LastSeq  int64       `json:"last_seq"`
	LastHash string      `json:"last_hash"`
}

type PolicyBundle struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Version   string             `json:"version"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PolicyBundleRule struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	PolicyBundleID pgtype.UUID        `json:"policy_bundle_id"`
	PolicyRuleID   pgtype.UUID        `json:"policy_rule_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PolicyRule struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Severity    string             `json:"severity"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RiverClient struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RiverClientQueue struct {
	RiverClientID    string             `json:"river_client_id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaxWorkers       int64              `json:"max_workers"`
	Metadata         []byte             `json:"metadata"`
	NumJobsCompleted int64              `json:"num_jobs_completed"`
	NumJobsRunning   int64              `json:"num_jobs_running"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RiverJob struct {
	ID           int64              `json:"id"`
	State        RiverJobState      `json:"state"`
	Attempt      int16              `json:"attempt"`
	MaxAttempts  int16              `json:"max_attempts"`
	AttemptedAt  pgtype.Timestamptz `json:"attempted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	Priority     int16              `json:"priority"`
	Args         []byte             `json:"args"`
	AttemptedBy  []string           `json:"attempted_by"`
	Errors       [][]byte           `json:"errors"`
	Kind         string             `json:"kind"`
	Metadata     []byte             `json:"metadata"`
	Queue        string             `json:"queue"`
	Tags         []string           `json:"tags"`
	UniqueKey    []byte             `json:"unique_key"`
	UniqueStates pgtype.Bits        `json:"unique_states"`
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz `json:"elected_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	LeaderID  string             `json:"leader_id"`
	Name      string             `json:"name"`
}

type RiverMigration struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Version   int64              `json:"version"`
}

type RiverQueue struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TenantApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	KeyHash    string             `json:"key_hash"`
	Label      string             `json:"label"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}
