// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPolicyBundleRule = `-- name: AddPolicyBundleRule :one
INSERT INTO policy_bundle_rules (tenant_id, policy_bundle_id, policy_rule_id)
VALUES ($1, $2, $3)
RETURNING tenant_id, policy_bundle_id, policy_rule_id, created_at
`

type AddPolicyBundleRuleParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	PolicyBundleID pgtype.UUID `json:"policy_bundle_id"`
	PolicyRuleID   pgtype.UUID `json:"policy_rule_id"`
}

func (q *Queries) AddPolicyBundleRule(ctx context.Context, arg AddPolicyBundleRuleParams) (PolicyBundleRule, error) {
	row := q.db.QueryRow(ctx, addPolicyBundleRule, arg.TenantID, arg.PolicyBundleID, arg.PolicyRuleID)
	var i PolicyBundleRule
	err := row.Scan(
		&i.TenantID,
		&i.PolicyBundleID,
		&i.PolicyRuleID,
		&i.CreatedAt,
	)
	return i, err
}

const createPolicyBundle = `-- name: CreatePolicyBundle :one
INSERT INTO policy_bundles (tenant_id, name, version, status)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, version, status, created_at
`

type CreatePolicyBundleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Version  string      `json:"version"`
	Status   string      `json:"status"`
}

func (q *Queries) CreatePolicyBundle(ctx context.Context, arg CreatePolicyBundleParams) (PolicyBundle, error) {
	row := q.db.QueryRow(ctx, createPolicyBundle,
		arg.TenantID,
		arg.Name,
		arg.Version,
		arg.Status,
	)
	var i PolicyBundle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPolicyRule = `-- name: CreatePolicyRule :one
INSERT INTO policy_rules (code, title, description, severity)
VALUES ($1, $2, $3, $4)
RETURNING id, code, title, description, severity, created_at
`

type CreatePolicyRuleParams struct {
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Severity    string `json:"severity"`
}

func (q *Queries) CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error) {
	row := q.db.QueryRow(ctx, createPolicyRule,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Severity,
	)
	var i PolicyRule
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CreatedAt,
	)
	return i, err
}

const listPolicyBundleRulesByTenant = `-- name: ListPolicyBundleRulesByTenant :many
SELECT pbr.tenant_id, pbr.policy_bundle_id, pbr.policy_rule_id, pbr.created_at,
       pr.code, pr.title, pr.description, pr.severity
FROM policy_bundle_rules pbr
JOIN policy_rules pr ON pr.id = pbr.policy_rule_id
WHERE pbr.tenant_id = $1
ORDER BY pr.code
`

type ListPolicyBundleRulesByTenantRow struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	PolicyBundleID pgtype.UUID        `json:"policy_bundle_id"`
	PolicyRuleID   pgtype.UUID        `json:"policy_rule_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Severity       string             `json:"severity"`
}

func (q *Queries) ListPolicyBundleRulesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListPolicyBundleRulesByTenantRow, error) {
	rows, err := q.db.Query(ctx, listPolicyBundleRulesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPolicyBundleRulesByTenantRow
	for rows.Next() {
		var i ListPolicyBundleRulesByTenantRow
		if err := rows.Scan(
			&i.TenantID,
			&i.PolicyBundleID,
			&i.PolicyRuleID,
			&i.CreatedAt,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
