// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPolicyBundleRule(ctx context.Context, arg AddPolicyBundleRuleParams) (PolicyBundleRule, error)
	// Scoped to (tenant_id, name): CreateBundleVersion numbers new versions per
	// bundle name, not globally per tenant.
	CountBundleVersions(ctx context.Context, arg CountBundleVersionsParams) (int64, error)
	CountOutOfHoursEvaluations(ctx context.Context) (int64, error)
	CreateDebtor(ctx context.Context, arg CreateDebtorParams) (CreateDebtorRow, error)
	CreateDetectorResultRow(ctx context.Context, arg CreateDetectorResultRowParams) (CreateDetectorResultRowRow, error)
	CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) (Evaluation, error)
	CreateInteractionEvent(ctx context.Context, arg CreateInteractionEventParams) (CreateInteractionEventRow, error)
	CreateInteractionTranscript(ctx context.Context, arg CreateInteractionTranscriptParams) (InteractionTranscript, error)
	CreatePolicyBundle(ctx context.Context, arg CreatePolicyBundleParams) (PolicyBundle, error)
	CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTenantAPIKey(ctx context.Context, arg CreateTenantAPIKeyParams) (TenantApiKey, error)
	// Resolves THE active bundle for a tenant (Design Decision 3/4): today's
	// BundleResolver seam resolves per-tenant only, with no bundle "name" input.
	// If a tenant were to ever activate more than one named bundle
	// simultaneously this returns a SQL "too many rows" error rather than
	// silently picking one; that constraint is out of scope for issue #6.
	GetActiveBundleByTenant(ctx context.Context, tenantID pgtype.UUID) (PolicyBundle, error)
	GetDebtorByTenant(ctx context.Context, arg GetDebtorByTenantParams) (GetDebtorByTenantRow, error)
	// Used by cmd/seed to detect whether a pre-existing (re-run) interaction
	// still needs to be backfilled with an evaluation.
	GetEvaluationByInteractionEventID(ctx context.Context, arg GetEvaluationByInteractionEventIDParams) (Evaluation, error)
	// Export endpoint lookup.
	GetEvidenceRecordByInteraction(ctx context.Context, arg GetEvidenceRecordByInteractionParams) (EvidenceRecord, error)
	// Evidence export lookup (issue #3): fetch a single interaction scoped to
	// its tenant.
	GetInteractionEventByID(ctx context.Context, arg GetInteractionEventByIDParams) (GetInteractionEventByIDRow, error)
	GetInteractionTranscriptByInteraction(ctx context.Context, arg GetInteractionTranscriptByInteractionParams) (InteractionTranscript, error)
	GetTenantAPIKeyByHash(ctx context.Context, keyHash string) (TenantApiKey, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	InsertEvidenceRecord(ctx context.Context, arg InsertEvidenceRecordParams) (EvidenceRecord, error)
	ListCurrentTenantInteractions(ctx context.Context, limit int32) ([]ListCurrentTenantInteractionsRow, error)
	// Issue #4 rewrite: aggregates across detector_result_rows per evaluation
	// (worst-severity-wins for the displayed reason, bool_or threat_flagged for
	// MX-REDECO-05) instead of assuming at most one detector result per
	// evaluation. One row per interaction — the LATERAL subquery collapses
	// every detector_result_rows child before the join, so a second
	// detector/judge result never fans out the interaction row.
	ListCurrentTenantInteractionsWithOutcome(ctx context.Context, limit int32) ([]ListCurrentTenantInteractionsWithOutcomeRow, error)
	ListDebtorsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListDebtorsByTenantRow, error)
	// Package detector layer for evidence export, sorted by detector_code.
	ListDetectorResultRowsByEvaluation(ctx context.Context, evaluationID pgtype.UUID) ([]ListDetectorResultRowsByEvaluationRow, error)
	ListDetectorResultRowsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListDetectorResultRowsByTenantRow, error)
	// Store-backed VerifyChain: replay a tenant's chain ordered by seq.
	ListEvidenceRecordsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]EvidenceRecord, error)
	ListInteractionEventsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListInteractionEventsByTenantRow, error)
	ListPolicyBundleRulesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListPolicyBundleRulesByTenantRow, error)
	ListTenantAPIKeysByTenant(ctx context.Context, tenantID pgtype.UUID) ([]TenantApiKey, error)
	// Insert-or-lock: first append inserts the genesis head; later appends take the
	// row lock via the no-op self-update. Either way returns the locked head.
	LockChainHead(ctx context.Context, arg LockChainHeadParams) (LockChainHeadRow, error)
	UpdateChainHead(ctx context.Context, arg UpdateChainHeadParams) error
}

var _ Querier = (*Queries)(nil)
