// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: redeco_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDespachoPenalizationsForPeriod = `-- name: DeleteDespachoPenalizationsForPeriod :exec
DELETE FROM despacho_penalizations
WHERE tenant_id = $1 AND period_year = $2 AND period_month = $3
`

type DeleteDespachoPenalizationsForPeriodParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	PeriodYear  int32       `json:"period_year"`
	PeriodMonth int32       `json:"period_month"`
}

func (q *Queries) DeleteDespachoPenalizationsForPeriod(ctx context.Context, arg DeleteDespachoPenalizationsForPeriodParams) error {
	_, err := q.db.Exec(ctx, deleteDespachoPenalizationsForPeriod, arg.TenantID, arg.PeriodYear, arg.PeriodMonth)
	return err
}

const listDespachoPenalizationsForPeriod = `-- name: ListDespachoPenalizationsForPeriod :many
SELECT id, tenant_id, despacho_id, complaint_case_id, period_year, period_month,
    penalization, resolution, source_state, created_at, updated_at
FROM despacho_penalizations
WHERE tenant_id = $1 AND period_year = $2 AND period_month = $3
ORDER BY despacho_id ASC, complaint_case_id ASC
`

type ListDespachoPenalizationsForPeriodParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	PeriodYear  int32       `json:"period_year"`
	PeriodMonth int32       `json:"period_month"`
}

func (q *Queries) ListDespachoPenalizationsForPeriod(ctx context.Context, arg ListDespachoPenalizationsForPeriodParams) ([]DespachoPenalization, error) {
	rows, err := q.db.Query(ctx, listDespachoPenalizationsForPeriod, arg.TenantID, arg.PeriodYear, arg.PeriodMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DespachoPenalization
	for rows.Next() {
		var i DespachoPenalization
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DespachoID,
			&i.ComplaintCaseID,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.Penalization,
			&i.Resolution,
			&i.SourceState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedecoMonthlyReportEntries = `-- name: ListRedecoMonthlyReportEntries :many
WITH latest_review AS (
    SELECT DISTINCT ON (hr.tenant_id, hr.complaint_case_id)
        hr.tenant_id,
        hr.complaint_case_id,
        hr.decision
    FROM human_reviews hr
    WHERE hr.processed_at IS NOT NULL
      AND hr.superseded_at IS NULL
    ORDER BY hr.tenant_id, hr.complaint_case_id, hr.processed_at DESC, hr.created_at DESC
)
SELECT
    cc.id AS complaint_case_id,
    cc.interaction_id,
    ie.despacho_id,
    COALESCE(d.display_name, 'unattributed')::text AS despacho_name,
    ie.channel,
    cc.redeco_cause AS cause,
    cc.state AS status,
    CASE
        WHEN cc.state = 'escalated' THEN 'escalated'
        WHEN latest_review.decision = 'approve' THEN 'approved'
        WHEN latest_review.decision = 'override' THEN 'overridden'
        ELSE 'resolved'
    END::text AS resolution,
    CASE
        WHEN cc.state = 'escalated' THEN 'penalized'
        WHEN latest_review.decision = 'override' THEN 'overridden'
        ELSE 'cleared'
    END::text AS penalization,
    ie.occurred_at,
    COALESCE(cc.resolved_at, cc.updated_at) AS closed_at
FROM complaint_cases cc
JOIN interaction_events ie ON ie.id = cc.interaction_id AND ie.tenant_id = cc.tenant_id
LEFT JOIN despachos d ON d.id = ie.despacho_id AND d.tenant_id = cc.tenant_id
LEFT JOIN latest_review ON latest_review.tenant_id = cc.tenant_id AND latest_review.complaint_case_id = cc.id
WHERE cc.tenant_id = $1
  AND cc.state IN ('resolved', 'escalated')
  AND COALESCE(cc.resolved_at, cc.updated_at) >= $2
  AND COALESCE(cc.resolved_at, cc.updated_at) < $3
ORDER BY closed_at ASC, cc.id ASC
`

type ListRedecoMonthlyReportEntriesParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	ResolvedAt_2 pgtype.Timestamptz `json:"resolved_at_2"`
}

type ListRedecoMonthlyReportEntriesRow struct {
	ComplaintCaseID pgtype.UUID        `json:"complaint_case_id"`
	InteractionID   pgtype.UUID        `json:"interaction_id"`
	DespachoID      pgtype.UUID        `json:"despacho_id"`
	DespachoName    string             `json:"despacho_name"`
	Channel         string             `json:"channel"`
	Cause           string             `json:"cause"`
	Status          string             `json:"status"`
	Resolution      string             `json:"resolution"`
	Penalization    string             `json:"penalization"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) ListRedecoMonthlyReportEntries(ctx context.Context, arg ListRedecoMonthlyReportEntriesParams) ([]ListRedecoMonthlyReportEntriesRow, error) {
	rows, err := q.db.Query(ctx, listRedecoMonthlyReportEntries, arg.TenantID, arg.ResolvedAt, arg.ResolvedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRedecoMonthlyReportEntriesRow
	for rows.Next() {
		var i ListRedecoMonthlyReportEntriesRow
		if err := rows.Scan(
			&i.ComplaintCaseID,
			&i.InteractionID,
			&i.DespachoID,
			&i.DespachoName,
			&i.Channel,
			&i.Cause,
			&i.Status,
			&i.Resolution,
			&i.Penalization,
			&i.OccurredAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDespachoPenalization = `-- name: UpsertDespachoPenalization :one
INSERT INTO despacho_penalizations (
    tenant_id, despacho_id, complaint_case_id, period_year, period_month,
    penalization, resolution, source_state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id, complaint_case_id, period_year, period_month) DO UPDATE
SET despacho_id = EXCLUDED.despacho_id,
    penalization = EXCLUDED.penalization,
    resolution = EXCLUDED.resolution,
    source_state = EXCLUDED.source_state,
    updated_at = now()
RETURNING id, tenant_id, despacho_id, complaint_case_id, period_year, period_month,
    penalization, resolution, source_state, created_at, updated_at
`

type UpsertDespachoPenalizationParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	DespachoID      pgtype.UUID `json:"despacho_id"`
	ComplaintCaseID pgtype.UUID `json:"complaint_case_id"`
	PeriodYear      int32       `json:"period_year"`
	PeriodMonth     int32       `json:"period_month"`
	Penalization    string      `json:"penalization"`
	Resolution      string      `json:"resolution"`
	SourceState     string      `json:"source_state"`
}

func (q *Queries) UpsertDespachoPenalization(ctx context.Context, arg UpsertDespachoPenalizationParams) (DespachoPenalization, error) {
	row := q.db.QueryRow(ctx, upsertDespachoPenalization,
		arg.TenantID,
		arg.DespachoID,
		arg.ComplaintCaseID,
		arg.PeriodYear,
		arg.PeriodMonth,
		arg.Penalization,
		arg.Resolution,
		arg.SourceState,
	)
	var i DespachoPenalization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DespachoID,
		&i.ComplaintCaseID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.Penalization,
		&i.Resolution,
		&i.SourceState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
