// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantAPIKey = `-- name: CreateTenantAPIKey :one
INSERT INTO tenant_api_keys (tenant_id, key_hash, label, status, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, key_hash, label, status, created_at, expires_at, last_used_at
`

type CreateTenantAPIKeyParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	KeyHash   string             `json:"key_hash"`
	Label     string             `json:"label"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTenantAPIKey(ctx context.Context, arg CreateTenantAPIKeyParams) (TenantApiKey, error) {
	row := q.db.QueryRow(ctx, createTenantAPIKey,
		arg.TenantID,
		arg.KeyHash,
		arg.Label,
		arg.Status,
		arg.ExpiresAt,
	)
	var i TenantApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getTenantAPIKeyByHash = `-- name: GetTenantAPIKeyByHash :one
SELECT id, tenant_id, key_hash, label, status, created_at, expires_at, last_used_at
FROM tenant_api_keys
WHERE key_hash = $1
`

func (q *Queries) GetTenantAPIKeyByHash(ctx context.Context, keyHash string) (TenantApiKey, error) {
	row := q.db.QueryRow(ctx, getTenantAPIKeyByHash, keyHash)
	var i TenantApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listTenantAPIKeysByTenant = `-- name: ListTenantAPIKeysByTenant :many
SELECT id, tenant_id, key_hash, label, status, created_at, expires_at, last_used_at
FROM tenant_api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTenantAPIKeysByTenant(ctx context.Context, tenantID pgtype.UUID) ([]TenantApiKey, error) {
	rows, err := q.db.Query(ctx, listTenantAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantApiKey
	for rows.Next() {
		var i TenantApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KeyHash,
			&i.Label,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
